---
- name: Deploy application
  hosts: docker
  tasks:
    - name: Clonar projeto
      git:
        repo: git@devops.dexter.com.br:devops/app.git
        dest: /root/app
        accept_hostkey: yes
        key_file: /etc/keys/key

    - name: Criar imagem
      command: docker build -t app .
      args:
        chdir: /root/app

    - name: Rodar docker-compose
      command: docker-compose up -d
      args:
        chdir: /root/app
