---
- name: Instalar agent do puppet
  hosts: automation
  tasks:
    - name: Baixar repositorio
      yum:
       name: https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
       state: present

    - name: Instalar puppet agent
      yum: "name={{ item }} state=present"
      with_items:
        - ntp
        - puppet

    - name: Conifigurar ntp
      command: ntpdate pool.ntp.org

    - name: Adicionar entrada etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "192.168.200.100 puppet"

    - name: Startar servico
      service:
        name: puppet
        state: started

    - name: Adicionar servico no boot da maquina
      command: systemctl enable puppet
